
package cxfAll;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2020-03-01T11:21:57.560+08:00
 * Generated source version: 3.1.4
 * 
 */
 
public class HelloWorld_HelloWorldImplPort_Server{

    protected HelloWorld_HelloWorldImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWorldImplPortImpl();
        String address = "http://127.0.0.1:8080/zpq-spring-ws-service/webservice/HelloWorld";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new HelloWorld_HelloWorldImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
