package cxfServer1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2020-03-01T11:21:11.138+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://impl.ad/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://ad/", className = "cxfServer1.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://ad/", className = "cxfServer1.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
