server:
  port: 3344

spring:
  application:
    name: config-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zpq5935/springcloud-config.git #配置文件所在仓库
#          username: 2251745121@qq.com
#          password: 54zpq5935
#          default-label: master #配置文件分支
#          search-paths: config  #配置文件所在根目录