
package cxfClient;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2020-02-19T12:38:08.757+08:00
 * Generated source version: 3.1.4
 * 
 */
 
public class HelloService_HelloServiceImplPort_Server{

    protected HelloService_HelloServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloServiceImplPortImpl();
        String address = "http://localhost:8081/ws/hello";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new HelloService_HelloServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
