
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cxfClient;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2020-02-19T12:38:08.749+08:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloServiceImplService",
                      portName = "HelloServiceImplPort",
                      targetNamespace = "http://service/",
                      wsdlLocation = "file:/C:/Users/zpq5935/Desktop/hello.wsdl",
                      endpointInterface = "cxfClient.HelloService")
                      
public class HelloServiceImplPortImpl implements HelloService {

    private static final Logger LOG = Logger.getLogger(HelloServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cxfClient.HelloService#sayHello(java.lang.String  arg0 )*
     */
    public java.lang.String sayHello(java.lang.String arg0) { 
        LOG.info("Executing operation sayHello");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
