server:
  port: 9002
spring:
  application:
    name: zuul-demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    demo1:
      path: /pro/**
      serviceId: provider
#  ignored-services: provider #忽略的服务

management:
  endpoints:
    web:
      exposure:
        include: routes,filters # 2.0版本 需要加这个配置